version: '3'

services:
  app:
    build:
      context: './php'
    container_name: app
    restart: always
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - '..:/var/www/html'
      - './php/local.ini:/usr/local/etc/php/conf.d/local.ini'
    networks:
        - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '..:/var/www/html'
      - './nginx/conf.d/:/etc/nginx/conf.d/'
    networks:
        - app-network

  db:
    image: mysql:8
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - './mysql/my.cnf:/etc/mysql/my.cnf'
    networks:
        - app-network

  pma:
    image: phpmyadmin:5.1
    container_name: pma
    restart: always
    environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - '8888:80'
    networks:
        - app-network

networks:
    app-network:
        driver: bridge
